version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "bun"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "bun"
    directory: "/packages/config"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "bun"
    directory: "/packages/db"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "bun"
    directory: "/packages/env"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
